(* ==========================================================================
 Nom d'unité :  cadet.inc
 Info Version  : contenu du fichier examap.h ; version Delphi
 Auteur(s) : Mehdi ALLAS, JF. PACORY, Mahmoud BOUKERROUI
 Etat :   A mettre à jour lors des modifications de l'aide
 --------------------------------------------------------------------------
 Révision(s) :
 ========================================================================== *)

     // contenu du fichier examap.h ; version Delphi
    IDH_PRESENTATION_APPLICATION = 100;

    IDH_INFORMATIONS_DE_BASE = 200;
    IDH_NOUVEAUTES = 210;
    IDH_REMERCIEMENTS = 220;
    IDH_CONTACTS_ET_INFORMATIONS = 230;

    IDH_UTILISER_APPLICATION = 300;
    IDH_PAGE_ACCUEIL = 310;
    IDH_PAGE_EXPRESSION = 320;
    IDH_PAGE_COMPILATION = 330;
    IDH_PAGE_CODE = 340;
    IDH_PAGE_EXECUTABLE = 350;
    IDH_PAGE_DESASSEMBLAGE = 360;
    IDH_PAGE_ANIMATION = 370;
    IDH_PAGE_DOCUMENTATION = 380;
    IDH_PAGE_A_PROPOS = 390;
    IDH_RACCOURCIS_CLAVIER = 395;

    IDH_DESCRIPTION_DES_MENUS = 400;
    IDH_MENU_FICHIER = 410;
    IDH_MENU_EDITION = 415;
    IDH_MENU_TRAITEMENTS= 425;
    IDH_MENU_AFFICHAGE = 420;
    IDH_MENU_AIDE = 430;

    IDH_PERSONNALISER_APPLICATION = 500;
